twig:
    file_name_pattern: '*.twig'
    globals:
        php_version: !php/const PHP_VERSION
        app_version: '%env(APP_VERSION)%'
        git_commit: '%env(GIT_COMMIT)%'

when@test:
    twig:
        strict_variables: true
